// <auto-generated />
using System;
using BlazorWebAssemblyCrud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebAssemblyCrud.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240518123233_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebAssemblyCrud.Shared.Entities.Artikul", b =>
                {
                    b.Property<int>("ArtikulID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikulID"));

                    b.Property<DateTime>("ArtikulDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtikulName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ArtikulPrice")
                        .HasColumnType("float");

                    b.HasKey("ArtikulID");

                    b.ToTable("artikuls");

                    b.HasData(
                        new
                        {
                            ArtikulID = 1,
                            ArtikulDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ArtikulName = "Televizor",
                            ArtikulPrice = 5.3300000000000001
                        },
                        new
                        {
                            ArtikulID = 2,
                            ArtikulDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ArtikulName = "Kasetofon",
                            ArtikulPrice = 6.5999999999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
